name: Generate Profile README (AI/ML)

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * *"   # run daily at 03:00 UTC
  push:
    branches:
      - main
      - master

permissions:
  contents: write
  metadata: read

jobs:
  build-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pygithub pyyaml

      - name: Ensure projects.json exists
        run: |
          if [ ! -f projects.json ]; then
            echo '{
              "projects": [
                "hardikko/AI-Career-Counselor",
                "hardikko/stock-market-prediction-LSTM",
                "hardikko/SignSpeak"
              ]
            }' > projects.json
            git add projects.json
            git commit -m "chore: add default projects.json" || echo "no commit"
          fi

      - name: Generate README and assets
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPLICATE_API_TOKEN: ${{ secrets.REPLICATE_API_TOKEN }}
          DEVTO_USERNAME: ${{ secrets.DEVTO_USERNAME }}
        run: |
          python - <<'PY'
# ------------------- Python Script -------------------
import json, os

with open("projects.json") as f:
    projects = json.load(f)["projects"]

readme_content = "# 👋 Hi, I'm Hardik Kothari\n\n"
readme_content += "## 🚀 Projects\n"
for proj in projects:
    readme_content += f"- [{proj}](https://github.com/{proj})\n"

with open("README.md", "w", encoding="utf-8") as f:
    f.write(readme_content)

print("✅ README.md generated successfully!")

# Git commit updated README
os.system("git add README.md")
os.system("git commit -m 'chore: auto-update README' || echo 'no changes'")
os.system("git push origin HEAD:main")
# -----------------------------------------------------
PY

      - name: Finished
        run: echo "🎉 README generation complete."
