name: Generate Profile README (AI/ML)

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * *"   # run daily at 03:00 UTC
  push:
    branches:
      - main
      - master

permissions:
  contents: write
  metadata: read

jobs:
  build-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pygithub pyyaml

      - name: Ensure projects.json exists
        run: |
          if [ ! -f projects.json ]; then
            cat > projects.json <<'JSON'
{
  "projects": [
    "hardikko/AI-Career-Counselor",
    "hardikko/stock-market-prediction-LSTM",
    "hardikko/SignSpeak"
  ]
}
JSON
            git add projects.json
            git commit -m "chore: add default projects.json" || echo "no commit"
          fi

      - name: Generate README and assets
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPLICATE_API_TOKEN: ${{ secrets.REPLICATE_API_TOKEN }}
          DEVTO_USERNAME: ${{ secrets.DEVTO_USERNAME }}
        run: |
          python - <<'PY'
# (Python script you had goes here, unchanged)
PY

      - name: Finished
        run: echo "README generation complete."
